// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPU-uSRm9-oWxNnda6PEJD_GBa1cZg4Q',
    appId: '1:251153496216:web:b0300bd306beca8c6278ed',
    messagingSenderId: '251153496216',
    projectId: 'anwarzeb1122',
    authDomain: 'anwarzeb1122.firebaseapp.com',
    storageBucket: 'anwarzeb1122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJyhYJiPIZI-gBzET7fJQcMGsidObuhQ',
    appId: '1:251153496216:android:19caf593d0cd83386278ed',
    messagingSenderId: '251153496216',
    projectId: 'anwarzeb1122',
    storageBucket: 'anwarzeb1122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcV8X0YcDFfDtKi9nffArmTW4O65prVY',
    appId: '1:251153496216:ios:eb880a07590e6f0e6278ed',
    messagingSenderId: '251153496216',
    projectId: 'anwarzeb1122',
    storageBucket: 'anwarzeb1122.firebasestorage.app',
    iosBundleId: 'com.example.examprep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcV8X0YcDFfDtKi9nffArmTW4O65prVY',
    appId: '1:251153496216:ios:eb880a07590e6f0e6278ed',
    messagingSenderId: '251153496216',
    projectId: 'anwarzeb1122',
    storageBucket: 'anwarzeb1122.firebasestorage.app',
    iosBundleId: 'com.example.examprep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbPU-uSRm9-oWxNnda6PEJD_GBa1cZg4Q',
    appId: '1:251153496216:web:06e9c559345278c66278ed',
    messagingSenderId: '251153496216',
    projectId: 'anwarzeb1122',
    authDomain: 'anwarzeb1122.firebaseapp.com',
    storageBucket: 'anwarzeb1122.firebasestorage.app',
  );
}
